version: 2
jobs:
  build:
    working_directory: ~/HelloWorldGitCircleCIAWS

    machine:
      environment:
        SPRING_PROFILES_ACTIVE: test
      timezone:
        America/Bogota
      # Here’s an example of how to set the version of Java to be used for your tests.
      java:
        version: openjdk8
      # You can enable other databases and services from the services section
      services:
        - docker

    general:
      artifacts:
        - "target/app.jar"

    steps:
      #In this case, the checkout step will checkout project source code into the job’s working_directory.
      - checkout
      - restore_cache:
          key: HelloWorldJavaGitCircleCIAWS-{{ checksum "pom.xml" }}
      - run: git config --global user.email jasonlll88@hotmail.com
      - run: git config --global user.name jasonlll88
      - run: mvn clean install

      - save_cache:
          # https://circleci.com/docs/2.0/caching/#caching-libraries MAVEN
          paths:
            - ~/.m2
          # https://circleci.com/docs/2.0/caching/#using-keys-and-templates
          # we can use the pom.xml  ????
          key: HelloWorldJavaGitCircleCIAWS-{{ checksum "pom.xml" }}

      - deploy:
         # name of the deploy
         name: Deploy HelloWorldJavaGitCircleCIAWS

         command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
              if [[ `git log -1` =~ "[maven-release-plugin]" ]]; then
                   echo "Ignoring release plugin generated version"
               else
                echo "Preparing release..."
                mvn -B release:prepare -Dmaven.test.skip=true

                JQ="jq -r -e"

                # assign the paramenters to some variables
                APP_NAME=helloworld
                CLUSTER_NAME=adapters
                ENVIRONMENT=prod
                VERSION="$(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version|grep -Ev '(^\[|Download\w+:)')"

                # Create other variables
                SERVICE_NAME="$ENVIRONMENT-accountopen-$APP_NAME-service"
                CLUSTER_NAME="bdb-accountopen-$ENVIRONMENT-$CLUSTER_NAME-cluster"
                BUILD_NUMBER=${CIRCLE_BUILD_NUM}
                IMAGE_TAG=${CIRCLE_SHA1}
                TASK_FAMILY="$ENVIRONMENT-accountopen-$APP_NAME-task-family"
                AWS_ACCOUNT_ID=058018423448

                if  [ ${ENVIRONMENT} = "prod" ]; then
                    export AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID_PROD
                    export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PROD
                    export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PROD
                fi

                # verify version of AWS
                aws --version
                # configure the dafult regiion
                aws configure set default.region us-east-1
                # configure the output format
                aws configure set default.output json

                # http://docs.aws.amazon.com/cli/latest/reference/ecr/get-login.html
                eval $(aws ecr get-login --region us-east-1)

                # Create a docker image from the source of this folder
                docker build -t $ENVIRONMENT-$APP_NAME .

                # # modify the tag of the image builded
                docker tag $ENVIRONMENT-$APP_NAME $AWS_ACCOUNT_ID.dkr.ecr.us-west-1.amazonaws.com/$ENVIRONMENT-$APP_NAME:$VERSION

                docker images

                # # Push the docker image to the AWS instance
                docker push $AWS_ACCOUNT_ID.dkr.ecr.us-west-1.amazonaws.com/$ENVIRONMENT-$APP_NAME:$VERSION

              fi
            else
              echo "Not deploy in master"
            fi



      # chmod 755 deploy.sh && ./deploy.sh HelloWorldJavaGitCircleCIAWS adapters prod "$(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version|grep -Ev '(^\[|Download\w+:)')"
      #JQ="jq -r -e"


      ###### sonar

      # - run:
      #     name: SONAR
      #     # if the branch is master then run
      #     command:|
      #       if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #                     mvn sonar:sonar -s settings_sonar.xml
      #       fi


#     docker:
#       - image: circleci/openjdk:8-jdk-browsers
#     steps:
#       - checkout
#       # - run: echo "hello world"
#       - run: pwd
#       - run: ls
#       - run: cat README.md
#       - run: ls ../
#       - restore_cache:
#           key: HelloWorldJavaGitCircleCIAWS-{{ checksum "pom.xml" }}
#       - run: mvn dependency:go-offline
#       - run: mvn clean install
#       - save_cache:
#           paths:
#             - ~/.m2
#           key: HelloWorldJavaGitCircleCIAWS-{{ checksum "pom.xml" }}
#       - run: mvn test
#       - run: mvn package
# #      - run: mvn exec:java -Dexec.mainClass="main.java.HelloWorldGitCircleCIAWS"
# #      - run: mvn exec:java
#       - deploy:
#           name: Deploy HelloWorldJava
#           command: |
#             if [ "${CIRCLE_BRANCH}" == "master" ]; then
#               if [[ `git log -1` =~ "[maven-release-plugin]" ]]; then
#                    echo "Ignoring release plugin generated version"
#               else
#                 echo "Preparing release..."
#                 mvn -B release:prepare -Dmaven.test.skip=true -s settings.xml
#
#
#       - store_test_results:
#           path: target/surefire-reports
#       - store_artifacts:
#           path: target/demo-java-0.0.1-SNAPSHOT.jar
